/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as FreeLearningRouteImport } from './routes/free-learning'
import { Route as IndicesRouteImport } from './routes/indices'
import { Route as InsuranceRouteImport } from './routes/insurance'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as ShoppingRouteImport } from './routes/shopping'
import { Route as LearnTopicRouteImport } from './routes/learn.$topic'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const FreeLearningRoute = FreeLearningRouteImport.update({
  id: '/free-learning',
  path: '/free-learning',
  getParentRoute: () => rootRouteImport,
} as any)
const IndicesRoute = IndicesRouteImport.update({
  id: '/indices',
  path: '/indices',
  getParentRoute: () => rootRouteImport,
} as any)
const InsuranceRoute = InsuranceRouteImport.update({
  id: '/insurance',
  path: '/insurance',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ShoppingRoute = ShoppingRouteImport.update({
  id: '/shopping',
  path: '/shopping',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnTopicRoute = LearnTopicRouteImport.update({
  id: '/learn/$topic',
  path: '/learn/$topic',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/finance': typeof FinanceRoute
  '/free-learning': typeof FreeLearningRoute
  '/indices': typeof IndicesRoute
  '/insurance': typeof InsuranceRoute
  '/jobs': typeof JobsRoute
  '/shopping': typeof ShoppingRoute
  '/learn/$topic': typeof LearnTopicRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/finance': typeof FinanceRoute
  '/free-learning': typeof FreeLearningRoute
  '/indices': typeof IndicesRoute
  '/insurance': typeof InsuranceRoute
  '/jobs': typeof JobsRoute
  '/shopping': typeof ShoppingRoute
  '/learn/$topic': typeof LearnTopicRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/finance': typeof FinanceRoute
  '/free-learning': typeof FreeLearningRoute
  '/indices': typeof IndicesRoute
  '/insurance': typeof InsuranceRoute
  '/jobs': typeof JobsRoute
  '/shopping': typeof ShoppingRoute
  '/learn/$topic': typeof LearnTopicRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/finance'
    | '/free-learning'
    | '/indices'
    | '/insurance'
    | '/jobs'
    | '/shopping'
    | '/learn/$topic'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/finance'
    | '/free-learning'
    | '/indices'
    | '/insurance'
    | '/jobs'
    | '/shopping'
    | '/learn/$topic'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/finance'
    | '/free-learning'
    | '/indices'
    | '/insurance'
    | '/jobs'
    | '/shopping'
    | '/learn/$topic'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  FinanceRoute: typeof FinanceRoute
  FreeLearningRoute: typeof FreeLearningRoute
  IndicesRoute: typeof IndicesRoute
  InsuranceRoute: typeof InsuranceRoute
  JobsRoute: typeof JobsRoute
  ShoppingRoute: typeof ShoppingRoute
  LearnTopicRoute: typeof LearnTopicRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/free-learning': {
      id: '/free-learning'
      path: '/free-learning'
      fullPath: '/free-learning'
      preLoaderRoute: typeof FreeLearningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indices': {
      id: '/indices'
      path: '/indices'
      fullPath: '/indices'
      preLoaderRoute: typeof IndicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insurance': {
      id: '/insurance'
      path: '/insurance'
      fullPath: '/insurance'
      preLoaderRoute: typeof InsuranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shopping': {
      id: '/shopping'
      path: '/shopping'
      fullPath: '/shopping'
      preLoaderRoute: typeof ShoppingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$topic': {
      id: '/learn/$topic'
      path: '/learn/$topic'
      fullPath: '/learn/$topic'
      preLoaderRoute: typeof LearnTopicRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  FinanceRoute: FinanceRoute,
  FreeLearningRoute: FreeLearningRoute,
  IndicesRoute: IndicesRoute,
  InsuranceRoute: InsuranceRoute,
  JobsRoute: JobsRoute,
  ShoppingRoute: ShoppingRoute,
  LearnTopicRoute: LearnTopicRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
